const PATHNAME = {
  MAIN: '/',
  FIND_DATA: '/finn-data',
  SEARCH: '/finn-data/sok',
  USE_DATA: '/finn-data/bruke-data',
  DATAJEGEREN: '/finn-data/datajegeren',
  OFFER_DATA: '/tilby-data',
  HOW_TO_OFFER_DATA: '/tilby-data/hvordan-tilby-data',
  ABOUT: '/om-datafabrikken',
  NEWS: '/nyheter',
  COMMUNITY: '/datalandsbyen',
  COMMUNITY_POPULAR: '/datalandsbyen/populaer',
  COMMUNITY_RECENT: '/datalandsbyen/siste',
  COMMUNITY_TAGS: '/datalandsbyen/emneord',
  COMMUNITY_ABOUT: '/datalandsbyen/om-datalandsbyen',
  COMMUNITY_SEARCH: '/datalandsbyen/søk',
  DATA_SOURCES: '/datakilder',
  GUIDEANCE_AND_COMPETENCE: '/veiledere-og-kompetanse',
  PRIVATE_SECTOR: '/privat-sektor',
  CONTACT: '/kontakt',
  LEGAL_FRAMEWORK: '/juridiske-rammer-bruk-av-data',
  TEXT_FORMAT: '/tekst-format',
  DATASET_DETAILS: '/datasett',
  FDK_PUBLIC_SERVICES: '/public-services',
  FDK_DATA_SERVICES: '/dataservices',
  FDK_CONCEPTS: '/concepts',
  ORGANIZATION: '/virksomheter',
  METADATAQUALITY: '/metadatakvalitet',
  COURSES: '/kurs',
  GUIDANCE: '/veiledning',
  SITEMAP: '/nettstedkart',
  LEGAL_GUIDE: '/juridisk-veileder-for-datadeling',
};

// eslint-disable-next-line import/prefer-default-export
export { PATHNAME };
