name: Deploy to production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-and-deploy-production:
    name: Build, test, publish and deploy to production environment on merge to master branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud CLI for image-store
        uses: google-github-actions/auth@main
        with:
          credentials_json: ${{ secrets.GCP_SA_DATAFABRIKKEN_GCR_KEY }}

      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker eu.gcr.io

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eu.gcr.io/datafabrikken-infra/datafabrikken-veiviser-dele-data
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ github.sha }},priority=1000
            type=ref,event=branch

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args:  |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            PUBLIC_URL=https://datafabrikken.norge.no/veiviser-for-deling-av-data

      - name: Apply Helm template
        run: |
          helm repo add datafabrikken https://datadeling.github.io/helm-chart/
          helm fetch --untar --untardir ./helm datafabrikken/datafabrikken-veiviser-dele-data
          helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/datafabrikken-infra/datafabrikken-veiviser-dele-data:${{ steps.meta.outputs.version }}" \
          -f ./helm/datafabrikken-veiviser-dele-data/values/prod.yaml \
          ./helm/datafabrikken-veiviser-dele-data/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Setup gcloud CLI for deploy
        uses: google-github-actions/auth@main
        with:
          credentials_json: ${{ secrets.DATAFABRIKKEN_PROD_AUTODEPLOY }}

      - name: Deploy to GCP
        run: |
          gcloud container clusters get-credentials datafabrikken-prod --region europe-north1-a --project datafabrikken-prod
          kubectl apply -f ./kubectlapply.yaml --force
          if ! kubectl --namespace=prod rollout status deployment datafabrikken-veiviser-dele-data; then
            kubectl --namespace=prod rollout undo deployment datafabrikken-veiviser-dele-data
            kubectl --namespace=prod rollout status deployment datafabrikken-veiviser-dele-data
            exit 1
          fi

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          mention: 'channel'
          if_mention: failure
          status: ${{ job.status }}
          author_name: 'Application: datafabrikken-veiviser-dele-data | Environment: prod'
          fields: commit,author,workflow,message
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
